vich_uploader:
    db_driver: orm

    mappings:
        product_illustration:
            uri_prefix: "%app.path.product_illustration%"
            upload_destination: "%kernel.project_dir%/public%app.path.product_illustration%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
